### ISSUE TITLE
Update TWRP

### ISSUE THREAD

**Issue by xyzz** [xyzz/amonet#5]
Merge k4y0z changes into TWRP, this should be provided also as a separate update package for users with older TWRP to install.

- [ ] Backup/restore fixes
- [x] Rename devices so that amazon updates can be installed "safely"

**Comment by chaosmaster** [comment]
You can also take a look at this, https://github.com/chaosmaster/amonet/blob/mt8127-tank/META-INF/com/google/android/update-binary

should you also plan on updating the lk-payload.
